"""worker extended profile fields

Revision ID: 5f097868d696
Revises: 5c356fcb551f
Create Date: 2026-06-28 08:15:34.621066+00:00
"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = '5f097868d696'
down_revision: str | None = '5c356fcb551f'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('worker_profiles', sa.Column('full_name', sa.String(length=120), nullable=True))
    op.add_column('worker_profiles', sa.Column('name_kana', sa.String(length=120), nullable=True))
    op.add_column('worker_profiles', sa.Column('email', sa.String(length=255), nullable=True))
    op.add_column('worker_profiles', sa.Column('current_employer', sa.String(length=255), nullable=True))
    op.add_column('worker_profiles', sa.Column('current_employer_public', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('worker_profiles', sa.Column('prefecture', sa.String(length=64), nullable=True))
    op.add_column('worker_profiles', sa.Column('area', sa.String(length=120), nullable=True))
    op.add_column('worker_profiles', sa.Column('work_history', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False))
    op.add_column('worker_profiles', sa.Column('qualifications', postgresql.ARRAY(sa.Text()), server_default=sa.text("'{}'::text[]"), nullable=False))
    op.add_column('worker_profiles', sa.Column('skills', postgresql.ARRAY(sa.Text()), server_default=sa.text("'{}'::text[]"), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('worker_profiles', 'skills')
    op.drop_column('worker_profiles', 'qualifications')
    op.drop_column('worker_profiles', 'work_history')
    op.drop_column('worker_profiles', 'area')
    op.drop_column('worker_profiles', 'prefecture')
    op.drop_column('worker_profiles', 'current_employer_public')
    op.drop_column('worker_profiles', 'current_employer')
    op.drop_column('worker_profiles', 'email')
    op.drop_column('worker_profiles', 'name_kana')
    op.drop_column('worker_profiles', 'full_name')
    # ### end Alembic commands ###
