"""initial schema

Revision ID: e7b9856f81d3
Revises:
Create Date: 2026-06-27 09:35:39.566126+00:00
"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = 'e7b9856f81d3'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('phone_number', sa.String(length=32), nullable=False),
    sa.Column('user_type', sa.Enum('worker', 'contractor', 'admin', name='user_type'), nullable=False),
    sa.Column('status', sa.Enum('pending', 'approved', 'suspended', name='user_status'), server_default=sa.text("'pending'"), nullable=False),
    sa.Column('display_name', sa.String(length=120), nullable=False),
    sa.Column('preferred_language', sa.String(length=8), server_default=sa.text("'ja'"), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('phone_number', name=op.f('uq_users_phone_number'))
    )
    op.create_table('app_config',
    sa.Column('key', sa.String(length=128), nullable=False),
    sa.Column('value', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], name=op.f('fk_app_config_updated_by_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('key', name=op.f('pk_app_config'))
    )
    op.create_table('contractor_profiles',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('company_name', sa.String(length=255), nullable=False),
    sa.Column('contact_person', sa.String(length=120), nullable=False),
    sa.Column('prefecture', sa.String(length=64), nullable=False),
    sa.Column('address', sa.String(length=255), nullable=True),
    sa.Column('rating', sa.Numeric(precision=4, scale=2), server_default=sa.text('0'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_contractor_profiles_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', name=op.f('pk_contractor_profiles'))
    )
    op.create_table('documents',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('doc_type', sa.Enum('photo_id', 'residence_card_front', 'residence_card_back', 'qualification', 'insurance_proof', 'job_photo', name='doc_type'), nullable=False),
    sa.Column('storage_path', sa.String(length=512), nullable=False),
    sa.Column('review_status', sa.Enum('pending', 'approved', 'rejected', name='doc_review_status'), server_default=sa.text("'pending'"), nullable=False),
    sa.Column('review_note', sa.String(length=512), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_documents_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_documents'))
    )
    op.create_index(op.f('ix_documents_user_id'), 'documents', ['user_id'], unique=False)
    op.create_table('jobs',
    sa.Column('contractor_id', sa.Uuid(), nullable=False),
    sa.Column('trades', postgresql.ARRAY(sa.Text()), nullable=False),
    sa.Column('work_date', sa.Date(), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=False),
    sa.Column('prefecture', sa.String(length=64), nullable=False),
    sa.Column('area', sa.String(length=120), nullable=True),
    sa.Column('address', sa.String(length=255), nullable=True),
    sa.Column('daily_wage', sa.Integer(), nullable=False),
    sa.Column('headcount', sa.Integer(), server_default=sa.text('1'), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('open', 'filled', 'closed', 'canceled', name='job_status'), server_default=sa.text("'open'"), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['contractor_id'], ['users.id'], name=op.f('fk_jobs_contractor_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_jobs'))
    )
    op.create_index(op.f('ix_jobs_contractor_id'), 'jobs', ['contractor_id'], unique=False)
    op.create_index('ix_jobs_status_work_date_prefecture', 'jobs', ['status', 'work_date', 'prefecture'], unique=False)
    op.create_table('applications',
    sa.Column('job_id', sa.Uuid(), nullable=False),
    sa.Column('worker_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.Enum('applied', 'confirmed', 'rejected', 'withdrawn', name='application_status'), server_default=sa.text("'applied'"), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], name=op.f('fk_applications_job_id_jobs'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['worker_id'], ['users.id'], name=op.f('fk_applications_worker_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_applications')),
    sa.UniqueConstraint('job_id', 'worker_id', name='uq_applications_job_id_worker_id')
    )
    op.create_index(op.f('ix_applications_job_id'), 'applications', ['job_id'], unique=False)
    op.create_index('ix_applications_worker_id_status', 'applications', ['worker_id', 'status'], unique=False)
    op.create_table('worker_profiles',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('nationality', sa.String(length=2), nullable=False),
    sa.Column('worker_class', sa.Enum('employee', 'freelance', name='worker_class'), nullable=False),
    sa.Column('residence_card_front_doc_id', sa.Uuid(), nullable=True),
    sa.Column('residence_card_back_doc_id', sa.Uuid(), nullable=True),
    sa.Column('visa_expiry_date', sa.Date(), nullable=True),
    sa.Column('work_restriction', sa.String(length=255), nullable=True),
    sa.Column('has_insurance', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('trades', postgresql.ARRAY(sa.Text()), server_default=sa.text("'{}'::text[]"), nullable=False),
    sa.Column('tools', postgresql.ARRAY(sa.Text()), server_default=sa.text("'{}'::text[]"), nullable=False),
    sa.Column('trust_score', sa.Numeric(precision=4, scale=2), server_default=sa.text('0'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['residence_card_back_doc_id'], ['documents.id'], name=op.f('fk_worker_profiles_residence_card_back_doc_id_documents'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['residence_card_front_doc_id'], ['documents.id'], name=op.f('fk_worker_profiles_residence_card_front_doc_id_documents'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_worker_profiles_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', name=op.f('pk_worker_profiles'))
    )
    op.create_table('matchings',
    sa.Column('job_id', sa.Uuid(), nullable=False),
    sa.Column('worker_id', sa.Uuid(), nullable=False),
    sa.Column('application_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.Enum('confirmed', 'checked_in', 'completed', 'canceled', 'noshow', name='matching_status'), nullable=False),
    sa.Column('contract_type', sa.Enum('employment_daylabor', 'subcontract', name='contract_type'), nullable=False),
    sa.Column('daily_wage', sa.Integer(), nullable=False),
    sa.Column('platform_fee', sa.Integer(), nullable=False),
    sa.Column('fee_status', sa.Enum('unpaid', 'paid', name='fee_status'), server_default=sa.text("'unpaid'"), nullable=False),
    sa.Column('checked_in_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('withholding_tax', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('checkin_lat', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('checkin_lng', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], name=op.f('fk_matchings_application_id_applications'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], name=op.f('fk_matchings_job_id_jobs'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['worker_id'], ['users.id'], name=op.f('fk_matchings_worker_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_matchings'))
    )
    op.create_index('ix_matchings_job_id', 'matchings', ['job_id'], unique=False)
    op.create_index('ix_matchings_worker_id_status', 'matchings', ['worker_id', 'status'], unique=False)
    op.create_table('messages',
    sa.Column('matching_id', sa.Uuid(), nullable=False),
    sa.Column('sender_id', sa.Uuid(), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('was_filtered', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['matching_id'], ['matchings.id'], name=op.f('fk_messages_matching_id_matchings'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sender_id'], ['users.id'], name=op.f('fk_messages_sender_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_messages'))
    )
    op.create_index(op.f('ix_messages_matching_id'), 'messages', ['matching_id'], unique=False)
    op.create_table('reviews',
    sa.Column('matching_id', sa.Uuid(), nullable=False),
    sa.Column('reviewer_id', sa.Uuid(), nullable=False),
    sa.Column('reviewee_id', sa.Uuid(), nullable=False),
    sa.Column('direction', sa.Enum('contractor_to_worker', 'worker_to_contractor', name='review_direction'), nullable=False),
    sa.Column('rating', sa.SmallInteger(), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('tags', postgresql.ARRAY(sa.Text()), server_default=sa.text("'{}'::text[]"), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('rating BETWEEN 1 AND 5', name=op.f('ck_reviews_rating_between_1_and_5')),
    sa.ForeignKeyConstraint(['matching_id'], ['matchings.id'], name=op.f('fk_reviews_matching_id_matchings'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reviewee_id'], ['users.id'], name=op.f('fk_reviews_reviewee_id_users'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reviewer_id'], ['users.id'], name=op.f('fk_reviews_reviewer_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_reviews')),
    sa.UniqueConstraint('matching_id', 'direction', name='uq_reviews_matching_id_direction')
    )
    op.create_index(op.f('ix_reviews_matching_id'), 'reviews', ['matching_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_reviews_matching_id'), table_name='reviews')
    op.drop_table('reviews')
    op.drop_index(op.f('ix_messages_matching_id'), table_name='messages')
    op.drop_table('messages')
    op.drop_index('ix_matchings_worker_id_status', table_name='matchings')
    op.drop_index('ix_matchings_job_id', table_name='matchings')
    op.drop_table('matchings')
    op.drop_table('worker_profiles')
    op.drop_index('ix_applications_worker_id_status', table_name='applications')
    op.drop_index(op.f('ix_applications_job_id'), table_name='applications')
    op.drop_table('applications')
    op.drop_index('ix_jobs_status_work_date_prefecture', table_name='jobs')
    op.drop_index(op.f('ix_jobs_contractor_id'), table_name='jobs')
    op.drop_table('jobs')
    op.drop_index(op.f('ix_documents_user_id'), table_name='documents')
    op.drop_table('documents')
    op.drop_table('contractor_profiles')
    op.drop_table('app_config')
    op.drop_table('users')
    # ### end Alembic commands ###

    # Native PostgreSQL enum types are created implicitly by create_table on
    # upgrade but are NOT dropped by drop_table — drop them explicitly so the
    # migration fully reverses and a subsequent upgrade re-creates them cleanly.
    for enum_name in (
        "user_type",
        "user_status",
        "worker_class",
        "doc_type",
        "doc_review_status",
        "job_status",
        "application_status",
        "matching_status",
        "contract_type",
        "fee_status",
        "review_direction",
    ):
        op.execute(f"DROP TYPE IF EXISTS {enum_name}")
