"""saved_jobs table

Revision ID: 5c356fcb551f
Revises: cceaccafd93c
Create Date: 2026-06-28 04:19:26.177382+00:00
"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = '5c356fcb551f'
down_revision: str | None = 'cceaccafd93c'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('saved_jobs',
    sa.Column('worker_id', sa.Uuid(), nullable=False),
    sa.Column('job_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], name=op.f('fk_saved_jobs_job_id_jobs'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['worker_id'], ['users.id'], name=op.f('fk_saved_jobs_worker_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_saved_jobs')),
    sa.UniqueConstraint('worker_id', 'job_id', name='uq_saved_jobs_worker_id_job_id')
    )
    op.create_index(op.f('ix_saved_jobs_job_id'), 'saved_jobs', ['job_id'], unique=False)
    op.create_index('ix_saved_jobs_worker_id_created_at', 'saved_jobs', ['worker_id', 'created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_saved_jobs_worker_id_created_at', table_name='saved_jobs')
    op.drop_index(op.f('ix_saved_jobs_job_id'), table_name='saved_jobs')
    op.drop_table('saved_jobs')
    # ### end Alembic commands ###
