"""profile bio and experience fields

Revision ID: 0f51f4e75385
Revises: 6d22c248e7a9
Create Date: 2026-06-28 02:11:14.916317+00:00
"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = '0f51f4e75385'
down_revision: str | None = '6d22c248e7a9'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contractor_profiles', sa.Column('bio', sa.Text(), nullable=True))
    op.add_column('worker_profiles', sa.Column('bio', sa.Text(), nullable=True))
    op.add_column('worker_profiles', sa.Column('years_experience', sa.Integer(), server_default=sa.text('0'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('worker_profiles', 'years_experience')
    op.drop_column('worker_profiles', 'bio')
    op.drop_column('contractor_profiles', 'bio')
    # ### end Alembic commands ###
