"""matching completion_requested_at

Revision ID: 6d22c248e7a9
Revises: e7b9856f81d3
Create Date: 2026-06-27 10:10:41.896737+00:00
"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = '6d22c248e7a9'
down_revision: str | None = 'e7b9856f81d3'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('matchings', sa.Column('completion_requested_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('matchings', 'completion_requested_at')
    # ### end Alembic commands ###
